"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import public_input_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EtlOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ModelInput(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ROOM_TYPE_FIELD_NUMBER: builtins.int
        BEDROOMS_FIELD_NUMBER: builtins.int
        BATHROOMS_FIELD_NUMBER: builtins.int
        ACCOMMODATES_FIELD_NUMBER: builtins.int
        BEDS_FIELD_NUMBER: builtins.int
        NEIGHBOURHOOD_FIELD_NUMBER: builtins.int
        LATITUDE_FIELD_NUMBER: builtins.int
        LONGITUDE_FIELD_NUMBER: builtins.int
        TV_FIELD_NUMBER: builtins.int
        ELEVATOR_FIELD_NUMBER: builtins.int
        INTERNET_FIELD_NUMBER: builtins.int
        room_type: builtins.int
        bedrooms: builtins.int
        bathrooms: builtins.float
        accommodates: builtins.int
        beds: builtins.int
        neighbourhood: builtins.int
        latitude: builtins.float
        longitude: builtins.float
        tv: builtins.bool
        elevator: builtins.bool
        internet: builtins.bool
        def __init__(
            self,
            *,
            room_type: builtins.int = ...,
            bedrooms: builtins.int = ...,
            bathrooms: builtins.float = ...,
            accommodates: builtins.int = ...,
            beds: builtins.int = ...,
            neighbourhood: builtins.int = ...,
            latitude: builtins.float = ...,
            longitude: builtins.float = ...,
            tv: builtins.bool = ...,
            elevator: builtins.bool = ...,
            internet: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["accommodates", b"accommodates", "bathrooms", b"bathrooms", "bedrooms", b"bedrooms", "beds", b"beds", "elevator", b"elevator", "internet", b"internet", "latitude", b"latitude", "longitude", b"longitude", "neighbourhood", b"neighbourhood", "room_type", b"room_type", "tv", b"tv"]) -> None: ...

    REQUEST_FIELD_NUMBER: builtins.int
    MODEL_INPUT_FIELD_NUMBER: builtins.int
    @property
    def request(self) -> public_input_pb2.Request: ...
    @property
    def model_input(self) -> global___EtlOutput.ModelInput: ...
    def __init__(
        self,
        *,
        request: public_input_pb2.Request | None = ...,
        model_input: global___EtlOutput.ModelInput | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_input", b"model_input", "request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["model_input", b"model_input", "request", b"request"]) -> None: ...

global___EtlOutput = EtlOutput

@typing_extensions.final
class ModelOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_FIELD_NUMBER: builtins.int
    PRICE_CATEGORY_FIELD_NUMBER: builtins.int
    @property
    def request(self) -> public_input_pb2.Request: ...
    price_category: builtins.int
    def __init__(
        self,
        *,
        request: public_input_pb2.Request | None = ...,
        price_category: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["price_category", b"price_category", "request", b"request"]) -> None: ...

global___ModelOutput = ModelOutput
