repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: "^.vscode/.*$"
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
    -   id: gitleaks
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        exclude: "(?x)^(.*_pb2.py|.*_pb2.pyi|.*_pb2_grpc.py)$"
    -   id: black-jupyter
        exclude: "(?x)^(.*_pb2.py|.*_pb2.pyi|.*_pb2_grpc.py)$"
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: "(?x)^(.*_pb2.py|.*_pb2_grpc.py)$"
        additional_dependencies:
        - flake8-comprehensions==3.10.1
        - flake8-tidy-imports==4.8.0
        - flake8-bugbear==22.12.6
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        name: mypy
        args:
        - --ignore-missing-imports
        - --disallow-incomplete-defs
        - --no-strict-optional
        additional_dependencies:
        - types-PyYAML
        - types-attrs
        - types-protobuf
        - types-setuptools
        - types-filelock
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --py36-plus
        exclude: "(?x)^(\n    .*_pb2.py|\n    .*_pb2_grpc.py\n)$\n"
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-mock-methods
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==22.12.0
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        exclude: "(?x)^(.*_pb2.py|.*_pb2_grpc.py)$"
        args:
        - --profile
        - black
        - --filter-files
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.0'
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
    -   id: dead
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        exclude: "(?x)^(.*_pb2.py|.*_pb2_grpc.py)$"
        args:
        - --disable=import-error
