# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal_nodes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_input_pb2 as public__input__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal_nodes.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14internal_nodes.proto\x1a\x12public_input.proto\"\xb4\x02\n\tEtlOutput\x12$\n\x07request\x18\x01 \x01(\x0b\x32\x13.entrypoint.Request\x12*\n\x0bmodel_input\x18\x02 \x01(\x0b\x32\x15.EtlOutput.ModelInput\x1a\xd4\x01\n\nModelInput\x12\x11\n\troom_type\x18\x01 \x01(\x05\x12\x10\n\x08\x62\x65\x64rooms\x18\x02 \x01(\x05\x12\x11\n\tbathrooms\x18\x03 \x01(\x02\x12\x14\n\x0c\x61\x63\x63ommodates\x18\x04 \x01(\x05\x12\x0c\n\x04\x62\x65\x64s\x18\x05 \x01(\x05\x12\x15\n\rneighbourhood\x18\x06 \x01(\x05\x12\x10\n\x08latitude\x18\x07 \x01(\x02\x12\x11\n\tlongitude\x18\x08 \x01(\x02\x12\n\n\x02tv\x18\t \x01(\x08\x12\x10\n\x08\x65levator\x18\n \x01(\x08\x12\x10\n\x08internet\x18\x0b \x01(\x08\"K\n\x0bModelOutput\x12$\n\x07request\x18\x01 \x01(\x0b\x32\x13.entrypoint.Request\x12\x16\n\x0eprice_category\x18\x02 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[public__input__pb2.DESCRIPTOR,])




_ETLOUTPUT_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='EtlOutput.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_type', full_name='EtlOutput.ModelInput.room_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bedrooms', full_name='EtlOutput.ModelInput.bedrooms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bathrooms', full_name='EtlOutput.ModelInput.bathrooms', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accommodates', full_name='EtlOutput.ModelInput.accommodates', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beds', full_name='EtlOutput.ModelInput.beds', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbourhood', full_name='EtlOutput.ModelInput.neighbourhood', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='EtlOutput.ModelInput.latitude', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='EtlOutput.ModelInput.longitude', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tv', full_name='EtlOutput.ModelInput.tv', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevator', full_name='EtlOutput.ModelInput.elevator', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internet', full_name='EtlOutput.ModelInput.internet', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=353,
)

_ETLOUTPUT = _descriptor.Descriptor(
  name='EtlOutput',
  full_name='EtlOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='EtlOutput.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_input', full_name='EtlOutput.model_input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ETLOUTPUT_MODELINPUT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=353,
)


_MODELOUTPUT = _descriptor.Descriptor(
  name='ModelOutput',
  full_name='ModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='ModelOutput.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_category', full_name='ModelOutput.price_category', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=430,
)

_ETLOUTPUT_MODELINPUT.containing_type = _ETLOUTPUT
_ETLOUTPUT.fields_by_name['request'].message_type = public__input__pb2._REQUEST
_ETLOUTPUT.fields_by_name['model_input'].message_type = _ETLOUTPUT_MODELINPUT
_MODELOUTPUT.fields_by_name['request'].message_type = public__input__pb2._REQUEST
DESCRIPTOR.message_types_by_name['EtlOutput'] = _ETLOUTPUT
DESCRIPTOR.message_types_by_name['ModelOutput'] = _MODELOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EtlOutput = _reflection.GeneratedProtocolMessageType('EtlOutput', (_message.Message,), {

  'ModelInput' : _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), {
    'DESCRIPTOR' : _ETLOUTPUT_MODELINPUT,
    '__module__' : 'internal_nodes_pb2'
    # @@protoc_insertion_point(class_scope:EtlOutput.ModelInput)
    })
  ,
  'DESCRIPTOR' : _ETLOUTPUT,
  '__module__' : 'internal_nodes_pb2'
  # @@protoc_insertion_point(class_scope:EtlOutput)
  })
_sym_db.RegisterMessage(EtlOutput)
_sym_db.RegisterMessage(EtlOutput.ModelInput)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUT,
  '__module__' : 'internal_nodes_pb2'
  # @@protoc_insertion_point(class_scope:ModelOutput)
  })
_sym_db.RegisterMessage(ModelOutput)


# @@protoc_insertion_point(module_scope)
