---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: demo
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: demo-tls-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: back
                port:
                  number: 80
            path: /api
            pathType: ImplementationSpecific
          - backend:
              service:
                name: front
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
