apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: demo-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: konstellation@intelygenz.com
    privateKeySecretRef:
      name: demo-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
