name: Deploy Demo GKE

on: workflow_dispatch

jobs:
  deploy-demo:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: chrisdickinson/setup-yq@latest

      - name: Setup environment
        run: |
          yq w -i ./demo/deploy/frontend.yaml "spec.template.spec.containers.[0].image" "konstellation/demo-front:${GITHUB_REF#refs/tags/demo-v}"
          yq w -i ./demo/deploy/backend.yaml "spec.template.spec.containers.[0].image" "konstellation/demo-back:${GITHUB_REF#refs/tags/demo-v}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: Get GKE Cluster Kubeconfig
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: konstellation-demo
          location: ${{ secrets.GCP_ZONE }}

      - uses: azure/setup-kubectl@v2.0

      - name: Google Cloud Deploy
        run: |
          kubectl create ns demo --dry-run -o yaml | kubectl apply -f -
          kubectl -n demo apply -f ./app/deploy/
